### ISSUE TITLE
Helper script to run on nonhuman data

### ISSUE THREAD

**Issue by mchaisso** [vpc-ccg/sedef#12]
I'd like to run on nonhuman genomes, but I'm too lazy to do anything to adapt the code to handle contigs that do not start "chr", or to run the manual transmission commands listed in the readme. Can you write a shell script to run this on files that start with any chromosome name?

**Comment by calkan** [comment]
doesn't this help?:

" You can pass a regex to parameter -e / --exclude to sedef.sh to modify this criteria. For example, to use FASTAs with NCBI format pass -e "^[0-9A-Z]+$"."

**Comment by mchaisso** [comment]
Yes and no. First, the regex specifies contigs to include, so the option is
strange. Next, just add an option that says "--all", so I don't have to
write -e "^.*". If no valid contigs are found, a help message about
specifying "--all" should be printed.

**Comment by mchaisso** [comment]
Otherwise, pretty glad to have this method out there, nobody wants to wgac.

**Comment by calkan** [comment]
ok, assigning @inumanag since I have no knowledge of the inner workings of the code

**Comment by inumanag** [comment]
Please try `-t translation.fa` (this was added to support non-human genomes and various in-house assemblies). Let me know if it works!

**Comment by inumanag** [comment]
3d67e9d fixed this
