### ISSUE TITLE
Downside to increasing the number of align buckets?

### ISSUE THREAD

**Issue by mrvollger** [vpc-ccg/sedef#16]
Hi,

Is there any downside to increasing the number of align buckets? With my particular assembly the last two align jobs are running for hours after everything else is done so I was hoping to increase the number of buckets to improve full CPU usage. 

Thanks!
Mitchell

**Comment by inumanag** [comment]
The only downside is that your file system might not be happy with too many files, so keep the number of buckets <100k. Parameters are currently tuned for hg19, so feel free to adjust them if they do not make sense for other genomes.

**Comment by mrvollger** [comment]
Great, thanks!
