### ISSUE TITLE
Error with number of jobs completed (zebrafish genome)

### ISSUE THREAD

**Issue by jmuribes** [vpc-ccg/sedef#22]
Hello,

I have run sedef on the zebrafish reference without issues in the past, but I tried running it using a recently published version of its chromosome 4 (reference: https://www.nature.com/articles/s41586-020-2962-9, Supplementary Dataset 1) and the job fails to complete.

First, I soft-masked the sequence of the new chromosome using RepeatMasker and then used that file for sedef. The issue seems to be with 2 align jobs that do not finish and indicate the exit non-zero status 1. The log file indicates “Error:vector:_M_default_append” (log file attached).

Any ideas or suggestions about what could be going on?

Thank you in advance for the help!

![sedef_zfish_error](https://user-images.githubusercontent.com/35707540/115285063-4be16000-a102-11eb-93c2-48f77f183827.png)
[bucket_0210.log](https://github.com/vpc-ccg/sedef/files/6338239/bucket_0210.log)

José

**Comment by inumanag** [comment]
Hi all,

can you please try BISER (https://github.com/0xTCG/biser/), which is a better version of SEDEF, and see if it works— it should be able to handle this issue? We are not maintaining SEDEF anymore.

**Comment by saraebell** [comment]
I am having issues installing BISER and therefore have continued to try and debug this issue with SEDEF, any possible suggestions?

Error: launched 1000 jobs but completed only 998 jobs; exiting...

**Comment by inumanag** [comment]
Hi @saraebell 

I have just fixed the issues with BISER. Can you please give it another try? 

This bug won't be fixed in SEDEF (but the fix is basically part of BISER).

**Comment by saraebell** [comment]
Yes, I can confirm that I successfully installed BISER.
