### ISSUE TITLE
regarding cigar string directions

### ISSUE THREAD

**Issue by yangyxt** [vpc-ccg/sedef#23]
Thank you for making this! 

I wonder which strand is the query strand and which strand is the ref strand for the cigar string in final table. SD1 or SD2 ?

Thanks!

**Comment by inumanag** [comment]
Hi @yangyxt 

SEDEF is now deprecated in favour of [BISER](https://github.com/0xTCG/biser/). 

As for your question: the query is the first mate, and the reference is the second mate.
