### ISSUE TITLE
Different output from published results

### ISSUE THREAD

**Issue by mchaisso** [vpc-ccg/sedef#24]
Hi, I'm trying to use sedef on mm8. There are a few missing dups:
-- downloaded from csail:
352991 mm8.bed
-- running sedef.sh with -j 16 as the only option
338320 out/mm8_final/final.bed

Some differences are expected over revisions, but there are some really large segdups that are missing.

The largest events with the corresponding line numbers are:

150493	178
150493	177
134550	846
134550	845
134492	3337
126247	3092
124653	1266
124653	1265
123007	2594
118273	2222

**Comment by inumanag** [comment]
Hi @mchaisso,

SEDEF is now deprecated. However, the reason for this behaviour (on top of my head, has been a long time since I implemented this) is probably due to the more stringent filtration of low-confidence SDs in later revisions.
